name: setup-pnpm
description: 🚙 reuse pnpm setup on CI over and over

inputs:
  node-version:
    description: Node.js version to use
    required: false
    default: current
  working-directory:
    description: Specify where to run the install command
    required: false
    default: .
  submodules:
    description: Checkout also submodules
    required: false
    default: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        submodules: ${{ inputs.submodules }}
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - uses: pnpm/action-setup@v3
      with:
        version: 9
        package_json_file: ${{ inputs.working-directory }}/package.json
    - run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: ${{ runner.os }}-pnpm-store-
    - run: pnpm i
      shell: bash
      working-directory: ${{ inputs.working-directory }}
